micronaut:
  application:
    name: demo
datasources:
  default:
    driver-class-name: org.h2.Driver
    schema-generate: CREATE_DROP
    dialect: H2
netty:
  default:
    allocator:
      max-order: 3
